# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Img2char < Formula
  desc "Convert monochrome PNG images to ASCII art using font pattern matching"
  homepage "https://github.com/yostos/img2char"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yostos/img2char/releases/download/v0.1.0/img2char_0.1.0_darwin_amd64.tar.gz"
      sha256 "a80bcb6ad9b80b57cdb0f2ef4d24af67a237d449b9a4426eb8918dd6a7b7d675"

      def install
        bin.install "img2char"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yostos/img2char/releases/download/v0.1.0/img2char_0.1.0_darwin_arm64.tar.gz"
      sha256 "da82b5740aa57f4bb150ceb625ace50efafd950af0a882bfb18b10e0fdf1a139"

      def install
        bin.install "img2char"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yostos/img2char/releases/download/v0.1.0/img2char_0.1.0_linux_amd64.tar.gz"
      sha256 "4707115c0e78ff0692e684a0bd98fc7a871c53617db32f8620ec1ea57c4cbad0"
      def install
        bin.install "img2char"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yostos/img2char/releases/download/v0.1.0/img2char_0.1.0_linux_arm64.tar.gz"
      sha256 "76c8575b072ea442fd0d113e874f687a0805b5e4d670d0bcef72583f360027bb"
      def install
        bin.install "img2char"
      end
    end
  end
end
